# config/services.yaml
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration for AccessDeniedListener
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Listener optimisé avec cache
    App\EventListener\UserActivityListener:
        arguments:
            $cache: '@cache.app'
            $logger: '@logger'
        tags:
            - { name: kernel.event_subscriber }